theme: jekyll-theme-cayman
title: "Neda Sardaripour's Research Portfolio"
description: "Exploring systems neuroscience and computational modeling at Vanderbilt University."
baseurl: "/neda.sardaripour.github.io"

